apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhobs-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhobs-prometheus
subjects:
- kind: ServiceAccount
  name: rhobs-prometheus    # 👈 prometheus should use this SA
  namespace: rhobs-po-demo  # 
