apiVersion: monitoring.rhobs/v1
# NOTE:               ☝️ ☝️ ☝️ rhobs and not .coreos.com

kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
